#pragma once
#include "nbt.h"
#include <cstdint>
#include <memory>

#define SLOT_EMPTY -1

std::shared_ptr<NbtTag> NbtItem(int8_t slot, int16_t id, int8_t count, int16_t damage);

enum Items : int16_t {
	ITEM_INVALID = -1,
	ITEM_MINIMUM = 255,
	ITEM_SHOVEL_IRON = 256,
	ITEM_PICKAXE_IRON,
	ITEM_AXE_IRON,
	ITEM_FLINT_AND_STEEL,
	ITEM_APPLE,
	ITEM_BOW,
	ITEM_ARROW,
	ITEM_COAL,
	ITEM_DIAMOND,
	ITEM_IRON,
	ITEM_GOLD,
	ITEM_SWORD_IRON,
	ITEM_SWORD_WOOD,
	ITEM_SHOVEL_WOOD,
	ITEM_PICKAXE_WOOD,
	ITEM_AXE_WOOD,
	ITEM_SWORD_STONE,
	ITEM_SHOVEL_STONE,
	ITEM_PICKAXE_STONE,
	ITEM_AXE_STONE,
	ITEM_SWORD_DIAMOND,
	ITEM_SHOVEL_DIAMOND,
	ITEM_PICKAXE_DIAMOND,
	ITEM_AXE_DIAMOND,
	ITEM_STICK,
	ITEM_BOWL,
	ITEM_MUSHROOM_STEW,
	ITEM_SWORD_GOLD,
	ITEM_SHOVEL_GOLD,
	ITEM_PICKAXE_GOLD,
	ITEM_AXE_GOLD,
	ITEM_STRING,
	ITEM_FEATHER,
	ITEM_GUNPOWDER,
	ITEM_HOE_WOOD,
	ITEM_HOE_STONE,
	ITEM_HOE_IRON,
	ITEM_HOE_DIAMOND,
	ITEM_HOE_GOLD,
	ITEM_SEEDS_WHEAT,
	ITEM_WHEAT,
	ITEM_BREAD,
	ITEM_HELMET_LEATHER,
	ITEM_CHESTPLATE_LEATHER,
	ITEM_LEGGINGS_LEATHER,
	ITEM_BOOTS_LEATHER,
	ITEM_HELMET_CHAINMAIL,
	ITEM_CHESTPLATE_CHAINMAIL,
	ITEM_LEGGINGS_CHAINMAIL,
	ITEM_BOOTS_CHAINMAIL,
	ITEM_HELMET_IRON,
	ITEM_CHESTPLATE_IRON,
	ITEM_LEGGINGS_IRON,
	ITEM_BOOT_IRON,
	ITEM_HELMET_DIAMOND,
	ITEM_CHESTPLATE_DIAMOND,
	ITEM_LEGGINGS_DIAMOND,
	ITEM_BOOT_DIAMOND,
	ITEM_HELMET_GOLD,
	ITEM_CHESTPLATE_GOLD,
	ITEM_LEGGINGS_GOLD,
	ITEM_BOOT_GOLD,
	ITEM_FLINT,
	ITEM_PORKCHOP,
	ITEM_PORKCHOP_COOKED,
	ITEM_PAINTING,
	ITEM_APPLE_GOLDEN,
	ITEM_SIGN,
	ITEM_DOOR_WOOD,
	ITEM_BUCKET,
	ITEM_BUCKET_WATER,
	ITEM_BUCKET_LAVA,
	ITEM_MINECART,
	ITEM_SADDLE,
	ITEM_DOOR_IRON,
	ITEM_REDSTONE,
	ITEM_SNOWBALL,
	ITEM_BOAT,
	ITEM_LEATHER,
	ITEM_BUCKET_MILK,
	ITEM_BRICK,
	ITEM_CLAY,
	ITEM_SUGARCANE,
	ITEM_PAPER,
	ITEM_BOOK,
	ITEM_SLIME,
	ITEM_MINECART_CHEST,
	ITEM_MINECART_FURNACE,
	ITEM_EGG,
	ITEM_COMPASS,
	ITEM_FISHING_ROD,
	ITEM_CLOCK,
	ITEM_GLOWSTONE_DUST,
	ITEM_FISH,
	ITEM_FISH_COOKED,
	ITEM_DYE,
	ITEM_BONE,
	ITEM_SUGAR,
	ITEM_CAKE,
	ITEM_BED,
	ITEM_REDSTONE_REPEATER,
	ITEM_COOKIE,
	ITEM_MAP,
	ITEM_SHEARS,
	ITEM_RECORD_13 = 2256,
	ITEM_RECORD_CAT = 2257,
	ITEM_MAX,
};

bool IsHoe(int16_t id);
bool CanPlace(int16_t id);
bool IsHoe(int16_t id);
bool IsSword(int16_t id);
bool IsPickaxe(int16_t id);
bool IsAxe(int16_t id);
bool IsShovel(int16_t id);
bool IsWeapon(int16_t id);
bool IsTool(int16_t id);
bool CanDamage(int16_t id);
bool IsThrowable(int16_t id);
bool IsItem(int16_t id);
bool IsBlock(int16_t id);
int16_t GetDamage(int16_t id);
int32_t GetMaxStack(int16_t id);